use dblab01;

create view IS_OLD_ACTOR(ACTID,ANAME,BYEAR,ISLEADNUM,BESTGRADE)
as select ACTOR.ACTID,ANAME,BYEAR,count(*),max(GRADE)
from ACTOR,ACTIN
where ACTIN.ACTID = ACTOR.ACTID and ISLEADING = 'Y' and BYEAR < 1990 and BYEAR >= 1980
group by (ACTOR.ACTID);